### ISSUE TITLE
Quick question on tool use

### ISSUE THREAD

**Issue by YahyaFarooqi** [emmamglass/reconstructor#5]
Quick question – are the models generated by this tool meant to be simulation ready? I am running multiple model reconstructions and all of them do not supply biomass requirements and hold no growth. Is this meant to occur, or am I perhaps using the tool incorrectly?

**Comment by emmamglass** [comment]
These models are meant to be simulation ready. It is now necessary to define a media condition when running the simulation; this is a new change that was made to the tool but the readme was not updated, so perhaps this is where your problem lies.

**Comment by YahyaFarooqi** [comment]
I have tried both with and without a medium defined (the documentation says it will fill in complete medium when no medium is defined). I still get no objective flux for either model. Maybe I am inputting the commands incorrectly?

`(reconstructor_env) nfarooqi@M4819 gsm % python -m reconstructor --input_file CNRZ32.faa --file_type 1 --gram positive --media 'cpd00001_e','cpd00009_e','cpd00023_e','cpd00029_e','cpd00033_e','cpd00035_e','cpd00039_e','cpd00041_e','cpd00051_e','cpd00053_e','cpd00054_e','cpd00060_e','cpd00065_e','cpd00066_e','cpd00067_e','cpd00069_e','cpd00084_e','cpd00092_e','cpd00104_e','cpd00107_e','cpd00119_e','cpd00128_e','cpd00129_e','cpd00132_e','cpd00137_e','cpd00156_e','cpd00161_e','cpd00207_e','cpd00208_e','cpd00215_e','cpd00218_e','cpd00220_e','cpd00305_e','cpd00322_e','cpd00393_e','cpd00443_e','cpd00644_e','cpd19013_e' --cpu 4


Using Gram positive objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 4 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to CNRZ32.KEGGprot.out 

Darwin
blasting CNRZ32.faa vs /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
diamond blastp -p 4 -d /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db -q CNRZ32.faa -o CNRZ32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['cpd00001_e', 'cpd00009_e', 'cpd00023_e', 'cpd00029_e', 'cpd00033_e', 'cpd00035_e', 'cpd00039_e', 'cpd00041_e', 'cpd00051_e', 'cpd00053_e', 'cpd00054_e', 'cpd00060_e', 'cpd00065_e', 'cpd00066_e', 'cpd00067_e', 'cpd00069_e', 'cpd00084_e', 'cpd00092_e', 'cpd00104_e', 'cpd00107_e', 'cpd00119_e', 'cpd00128_e', 'cpd00129_e', 'cpd00132_e', 'cpd00137_e', 'cpd00156_e', 'cpd00161_e', 'cpd00207_e', 'cpd00208_e', 'cpd00215_e', 'cpd00218_e', 'cpd00220_e', 'cpd00305_e', 'cpd00322_e', 'cpd00393_e', 'cpd00443_e', 'cpd00644_e', 'cpd19013_e']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[-----------------------------------------]
	Draft reconstruction had 519 genes, 587 reactions, and 725 metabolites
	Gapfilled 94 reactions and 51 metabolites

	Final reconstruction has 681 reactions and 776 metabolites
	Final objective flux is 0.0

Saving new GENRE to CNRZ32.sbml 

(reconstructor_env) nfarooqi@M4819 gsm % python -m reconstructor --input_file CNRZ32.faa --file_type 1 --gram positive --cpu 4          
 

Using Gram positive objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 4 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to CNRZ32.KEGGprot.out 

Darwin
blasting CNRZ32.faa vs /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
diamond blastp -p 4 -d /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db -q CNRZ32.faa -o CNRZ32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['default_media']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[-----------------------------------------]
	Draft reconstruction had 519 genes, 587 reactions, and 725 metabolites
	Gapfilled 90 reactions and 46 metabolites

	Final reconstruction has 677 reactions and 771 metabolites
	Final objective flux is 0.0

Saving new GENRE to CNRZ32.sbml `

**Comment by YahyaFarooqi** [comment]
I have tried both with and without a medium defined (the documentation says it will fill in complete medium when no medium is defined). I still get no objective flux for either model. Maybe I am inputting the commands incorrectly?
'
(reconstructor_env) nfarooqi@M4819 gsm % python -m reconstructor --input_file CNRZ32.faa --file_type 1 --gram positive --media 'cpd00001_e','cpd00009_e','cpd00023_e','cpd00029_e','cpd00033_e','cpd00035_e','cpd00039_e','cpd00041_e','cpd00051_e','cpd00053_e','cpd00054_e','cpd00060_e','cpd00065_e','cpd00066_e','cpd00067_e','cpd00069_e','cpd00084_e','cpd00092_e','cpd00104_e','cpd00107_e','cpd00119_e','cpd00128_e','cpd00129_e','cpd00132_e','cpd00137_e','cpd00156_e','cpd00161_e','cpd00207_e','cpd00208_e','cpd00215_e','cpd00218_e','cpd00220_e','cpd00305_e','cpd00322_e','cpd00393_e','cpd00443_e','cpd00644_e','cpd19013_e' --cpu 4

Using Gram positive objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 4 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to CNRZ32.KEGGprot.out

Darwin
blasting CNRZ32.faa vs /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
diamond blastp -p 4 -d /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db -q CNRZ32.faa -o CNRZ32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['cpd00001_e', 'cpd00009_e', 'cpd00023_e', 'cpd00029_e', 'cpd00033_e', 'cpd00035_e', 'cpd00039_e', 'cpd00041_e', 'cpd00051_e', 'cpd00053_e', 'cpd00054_e', 'cpd00060_e', 'cpd00065_e', 'cpd00066_e', 'cpd00067_e', 'cpd00069_e', 'cpd00084_e', 'cpd00092_e', 'cpd00104_e', 'cpd00107_e', 'cpd00119_e', 'cpd00128_e', 'cpd00129_e', 'cpd00132_e', 'cpd00137_e', 'cpd00156_e', 'cpd00161_e', 'cpd00207_e', 'cpd00208_e', 'cpd00215_e', 'cpd00218_e', 'cpd00220_e', 'cpd00305_e', 'cpd00322_e', 'cpd00393_e', 'cpd00443_e', 'cpd00644_e', 'cpd19013_e']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[-----------------------------------------]
Draft reconstruction had 519 genes, 587 reactions, and 725 metabolites
Gapfilled 94 reactions and 51 metabolites

Final reconstruction has 681 reactions and 776 metabolites
Final objective flux is 0.0
Saving new GENRE to CNRZ32.sbml

(reconstructor_env) nfarooqi@M4819 gsm % python -m reconstructor --input_file CNRZ32.faa --file_type 1 --gram positive --cpu 4

Using Gram positive objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 4 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to CNRZ32.KEGGprot.out

Darwin
blasting CNRZ32.faa vs /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
diamond blastp -p 4 -d /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db -q CNRZ32.faa -o CNRZ32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['default_media']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[-----------------------------------------]
Draft reconstruction had 519 genes, 587 reactions, and 725 metabolites
Gapfilled 90 reactions and 46 metabolites

Final reconstruction has 677 reactions and 771 metabolites
Final objective flux is 0.0
Saving new GENRE to CNRZ32.sbml 
'

**Comment by YahyaFarooqi** [comment]
I have tried both with and without a medium defined (the documentation says it will fill in complete medium when no medium is defined). I still get no objective flux for either model. Maybe I am inputting the commands incorrectly?

```
(reconstructor_env) nfarooqi@M4819 gsm % python -m reconstructor --input_file CNRZ32.faa --file_type 1 --gram positive --media 'cpd00001_e','cpd00009_e','cpd00023_e','cpd00029_e','cpd00033_e','cpd00035_e','cpd00039_e','cpd00041_e','cpd00051_e','cpd00053_e','cpd00054_e','cpd00060_e','cpd00065_e','cpd00066_e','cpd00067_e','cpd00069_e','cpd00084_e','cpd00092_e','cpd00104_e','cpd00107_e','cpd00119_e','cpd00128_e','cpd00129_e','cpd00132_e','cpd00137_e','cpd00156_e','cpd00161_e','cpd00207_e','cpd00208_e','cpd00215_e','cpd00218_e','cpd00220_e','cpd00305_e','cpd00322_e','cpd00393_e','cpd00443_e','cpd00644_e','cpd19013_e' --cpu 4

Using Gram positive objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 4 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to CNRZ32.KEGGprot.out

Darwin
blasting CNRZ32.faa vs /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
diamond blastp -p 4 -d /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db -q CNRZ32.faa -o CNRZ32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['cpd00001_e', 'cpd00009_e', 'cpd00023_e', 'cpd00029_e', 'cpd00033_e', 'cpd00035_e', 'cpd00039_e', 'cpd00041_e', 'cpd00051_e', 'cpd00053_e', 'cpd00054_e', 'cpd00060_e', 'cpd00065_e', 'cpd00066_e', 'cpd00067_e', 'cpd00069_e', 'cpd00084_e', 'cpd00092_e', 'cpd00104_e', 'cpd00107_e', 'cpd00119_e', 'cpd00128_e', 'cpd00129_e', 'cpd00132_e', 'cpd00137_e', 'cpd00156_e', 'cpd00161_e', 'cpd00207_e', 'cpd00208_e', 'cpd00215_e', 'cpd00218_e', 'cpd00220_e', 'cpd00305_e', 'cpd00322_e', 'cpd00393_e', 'cpd00443_e', 'cpd00644_e', 'cpd19013_e']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[-----------------------------------------]
Draft reconstruction had 519 genes, 587 reactions, and 725 metabolites
Gapfilled 94 reactions and 51 metabolites

Final reconstruction has 681 reactions and 776 metabolites
Final objective flux is 0.0
Saving new GENRE to CNRZ32.sbml

(reconstructor_env) nfarooqi@M4819 gsm % python -m reconstructor --input_file CNRZ32.faa --file_type 1 --gram positive --cpu 4

Using Gram positive objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 4 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to CNRZ32.KEGGprot.out

Darwin
blasting CNRZ32.faa vs /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
diamond blastp -p 4 -d /Users/nfarooqi/mambaforge/envs/reconstructor_env/lib/python3.9/site-packages/reconstructor/refs/screened_kegg_prokaryotes_pep_db -q CNRZ32.faa -o CNRZ32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['default_media']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[-----------------------------------------]
Draft reconstruction had 519 genes, 587 reactions, and 725 metabolites
Gapfilled 90 reactions and 46 metabolites

Final reconstruction has 677 reactions and 771 metabolites
Final objective flux is 0.0
Saving new GENRE to CNRZ32.sbml

```

**Comment by qikongwanli** [comment]
> I have tried both with and without a medium defined (the documentation says it will fill in complete medium when no medium is defined). I still get no objective flux for either model. Maybe I am inputting the commands incorrectly?

I faced the same issues that the final objective flux was 0 for all model I built.

**Comment by emmamglass** [comment]
We have just fixed this issue and updated reconstructor (new version is 1.1.0). The reaction bounds were incorrectly defined for incorporating media-associated exchange reactions, resulting in some models having a zero objective flux. Thank you for bringing this to our attention!

With this new fix, there is still a potential for the models to have a final objective flux of zero, if you are using a more constrained or minimal media condition. The models should have a non-zero objective flux if you are using a rich media condition. We have a built in rich media condition that you can define this way: --media rich

Further, this fix has no impact on the benchmarking scores for the reconstructor models, they are still of high quality. 

Let us know if there are any further questions related to this issue.

**Comment by qikongwanli** [comment]
> We have just fixed this issue and updated reconstructor (new version is 1.1.0). The reaction bounds were incorrectly defined for incorporating media-associated exchange reactions, resulting in some models having a zero objective flux. Thank you for bringing this to our attention!
> 
> With this new fix, there is still a potential for the models to have a final objective flux of zero, if you are using a more constrained or minimal media condition. The models should have a non-zero objective flux if you are using a rich media condition. We have a built in rich media condition that you can define this way: --media rich
> 
> Further, this fix has no impact on the benchmarking scores for the reconstructor models, they are still of high quality.
> 
> Let us know if there are any further questions related to this issue.

Hi Emma, thank you for your update. However, I encounter a new issue after updating the reconstructor to v1.1.0. The following is the code and issue report.

$python -m reconstructor --input_file bin.faa --file_type 1 --gram negative --cpu 10 --gapfill yes  --out bin.xml --exchange 1 --media rich

Using Gram negative objective function
Using minimum objective flux fraction of 0.01 and maximum fraction of 0.5
Using 10 processor(s)

Loading GENRE construction databases...
[-----------------------------------------]
Aligning peptide sequences to KEGG database, may take some time...
Saving BLASTp results to bin.32.KEGGprot.out

Windows
blasting bin.32.faa vs C:\ProgramData\miniconda3\envs\reconstuctor\Lib\site-packages\reconstructor/refs/screened_kegg_prokaryotes_pep_db
running blastp with the following command line...
C:\ProgramData\miniconda3\envs\reconstuctor\Lib\site-packages\reconstructor\diamond blastp -p 10 -d C:\ProgramData\miniconda3\envs\reconstuctor\Lib\site-packages\reconstructor/refs/screened_kegg_prokaryotes_pep_db -q bin.32.faa -o bin.32.KEGGprot.out --more-sensitive --max-target-seqs 1 --quiet
finished blast
Creating draft GENRE from BLAST results...
['rich']
Identifying new metabolism (Step 1 of 2)...
[-----------------------------------------]
set()
Identifying new metabolism (Step 2 of 2)...
[---------------                          ]Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\reconstructor\__main__.py", line 245, in _find_reactions
    universal.solver.update()
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\interface.py", line 1473, in update
    self._add_constraints(add_constr)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\glpk_interface.py", line 780, in _add_constraints
    self._glpk_set_row_bounds(constraint)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\glpk_interface.py", line 839, in _glpk_set_row_bounds
    raise Exception(
Exception: Something is wrong with the provided bounds nan and nan in constraint eda89d3f-cdb6-11ee-afd1-010101010000: nan <= 1.0*biomass_GmNeg - 1.0*biomass_GmNeg_reverse_cd371 <= nan

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\reconstructor\__main__.py", line 670, in <module>
    media_reactions = _find_reactions(filled_genre, universal, metabolic_tasks, universal_obj, min_frac, max_frac, 2, file_type)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\reconstructor\__main__.py", line 271, in _find_reactions
    solution = universal.optimize()
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\cobra\core\model.py", line 1228, in __exit__
    context.reset()
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\cobra\util\context.py", line 42, in reset
    entry()
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\cobra\util\solver.py", line 206, in reset
    model.solver.objective = reverse_value
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\glpk_interface.py", line 628, in objective
    super(Model, self.__class__).objective.fset(self, value)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\interface.py", line 1235, in objective
    self.update()
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\interface.py", line 1473, in update
    self._add_constraints(add_constr)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\glpk_interface.py", line 759, in _add_constraints
    super(Model, self)._add_constraints(constraints, sloppy=sloppy)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\interface.py", line 1582, in _add_constraints
    self._constraints.append(constraint)
  File "C:\ProgramData\miniconda3\envs\reconstuctor\lib\site-packages\optlang\container.py", line 172, in append
    raise ContainerAlreadyContains("Container '%s' already contains an object with name '%s'." % (self, value.name))
optlang.exceptions.ContainerAlreadyContains: Container '<optlang.container.Container object at 0x000001EB9A4041F0>' already contains an object with name 'eda89d3f-cdb6-11ee-afd1-010101010000'.

**Comment by abates20** [comment]
> However, I encounter a new issue after updating the reconstructor to v1.1.0.

I believe this new issue was fixed in v1.1.1. If you have any additional problems in v1.1.1 feel free to open a new issue.
